ironmailserver:
  extends:
    file: common-compose.yml
    service: ironmailserver
  links:
    - mongo
mongo:
  extends:
    file: common-compose.yml
    service: mongo
nginx:
  extends:
    file: common-compose.yml
    service: nginx
  links:
    - ironmailserver:ironmailserver
