ironmailserver:
  build: ./
  ports:
    - "3000"
  links:
    - mongo
mongo:
  image: mongo
nginx:
  build: ./nginx
  ports:
    - "80:80"
    - "443:443"
  links:
    - ironmailserver:ironmailserver
